### ISSUE TITLE
plug in problem

### ISSUE THREAD

**Issue by kenxxxxx** [TencentARC/ViT-Lens#11]
The tensor matrix output by vitlens is 1*768 for each modal message right? So where in Instructblip do I plug it in can you please answer? Thanks!

**Comment by StanLei52** [comment]
Hi, thank you for your question.

For InstructBLIP and SEED-LLaMA integration, we use [EVA-CLIP-g/14](https://github.com/TencentARC/ViT-Lens/blob/e39f35b09d8eacd6018aa7a4895b140b6c90a65e/vitlens/src/open_clip/third_vit/blip_eva_vit.py#L763)(embedding dim: 1408) for ViT-Lens training, which is different from `ViT-Lens-L` (based on ViT Large). Since we use the same ViT as InstructBLIP and SEED-LLaMA, we directly plug the Lens and modality module prior to ViT layers.

**Comment by kenxxxxx** [comment]
Thanks for your answer! Do you plan to upload the models used for integration?

> Hi, thank you for your question.
> 
> For InstructBLIP and SEED-LLaMA integration, we use [EVA-CLIP-g/14](https://github.com/TencentARC/ViT-Lens/blob/e39f35b09d8eacd6018aa7a4895b140b6c90a65e/vitlens/src/open_clip/third_vit/blip_eva_vit.py#L763)(embedding dim: 1408) for ViT-Lens training, which is different from `ViT-Lens-L` (based on ViT Large). Since we use the same ViT as InstructBLIP and SEED-LLaMA, we directly plug the Lens and modality module prior to ViT layers.

**Comment by StanLei52** [comment]
Yes. Currently some ckpt can be found on hf([3D](https://huggingface.co/TencentARC/ViT-Lens/blob/main/eva_g14_objaverse.pt)). I am working on cleaning the code for integration pipeline and plan to release it within one month due to limited bandwidth.

**Comment by kenxxxxx** [comment]
Okay thanks!

**Comment by cfeng16** [comment]
Nice work! I am wondering if there is any update regarding the release of code?
